openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: quotes-controller
    description: Quotes Controller
paths:
  /quotes:
    get:
      tags:
        - quotes-controller
      summary: getRandomQuote
      operationId: getRandomQuoteUsingGET
      parameters:
        - name: quote
          in: query
          description: quote
          required: false
          style: form
          schema:
            type: string
        - name: artist
          in: query
          description: artist
          required: false
          style: form
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Quotes'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    Quotes:
      title: Quotes
      type: object
      properties:
        artist:
          type: string
        id:
          type: integer
          format: int32
        quote:
          type: string
